<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mady Welch">

<title>Halloween Mini-Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Class10_render_files/libs/clipboard/clipboard.min.js"></script>
<script src="Class10_render_files/libs/quarto-html/quarto.js"></script>
<script src="Class10_render_files/libs/quarto-html/popper.min.js"></script>
<script src="Class10_render_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Class10_render_files/libs/quarto-html/anchor.min.js"></script>
<link href="Class10_render_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Class10_render_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Class10_render_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Class10_render_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Class10_render_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Halloween Mini-Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Mady Welch </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<section id="importing-candy-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-candy-data">Importing Candy Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>candy_file <span class="ot">&lt;-</span> <span class="st">"https://raw.githubusercontent.com/fivethirtyeight/data/master/candy-power-ranking/candy-data.csv"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">read.csv</span>(candy_file)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                competitorname chocolate fruity caramel peanutyalmondy nougat
1                    100 Grand         1      0       1              0      0
2                 3 Musketeers         1      0       0              0      1
3                     One dime         0      0       0              0      0
4                  One quarter         0      0       0              0      0
5                    Air Heads         0      1       0              0      0
6                   Almond Joy         1      0       0              1      0
7                    Baby Ruth         1      0       1              1      1
8           Boston Baked Beans         0      0       0              1      0
9                   Candy Corn         0      0       0              0      0
10          Caramel Apple Pops         0      1       1              0      0
11             Charleston Chew         1      0       0              0      1
12  Chewey Lemonhead Fruit Mix         0      1       0              0      0
13                    Chiclets         0      1       0              0      0
14                        Dots         0      1       0              0      0
15                    Dum Dums         0      1       0              0      0
16                 Fruit Chews         0      1       0              0      0
17                     Fun Dip         0      1       0              0      0
18                  Gobstopper         0      1       0              0      0
19           Haribo Gold Bears         0      1       0              0      0
20           Haribo Happy Cola         0      0       0              0      0
21           Haribo Sour Bears         0      1       0              0      0
22          Haribo Twin Snakes         0      1       0              0      0
23            HersheyÕs Kisses         1      0       0              0      0
24           HersheyÕs Krackel         1      0       0              0      0
25    HersheyÕs Milk Chocolate         1      0       0              0      0
26      HersheyÕs Special Dark         1      0       0              0      0
27                  Jawbusters         0      1       0              0      0
28                Junior Mints         1      0       0              0      0
29                     Kit Kat         1      0       0              0      0
30                 Laffy Taffy         0      1       0              0      0
31                   Lemonhead         0      1       0              0      0
32 Lifesavers big ring gummies         0      1       0              0      0
33         Peanut butter M&amp;MÕs         1      0       0              1      0
34                       M&amp;MÕs         1      0       0              0      0
35                  Mike &amp; Ike         0      1       0              0      0
36                   Milk Duds         1      0       1              0      0
37                   Milky Way         1      0       1              0      1
38          Milky Way Midnight         1      0       1              0      1
39    Milky Way Simply Caramel         1      0       1              0      0
40                      Mounds         1      0       0              0      0
41                 Mr Good Bar         1      0       0              1      0
42                       Nerds         0      1       0              0      0
43         Nestle Butterfinger         1      0       0              1      0
44               Nestle Crunch         1      0       0              0      0
45                   Nik L Nip         0      1       0              0      0
46                 Now &amp; Later         0      1       0              0      0
47                      Payday         0      0       0              1      1
48                 Peanut M&amp;Ms         1      0       0              1      0
49                Pixie Sticks         0      0       0              0      0
50                   Pop Rocks         0      1       0              0      0
51                   Red vines         0      1       0              0      0
52          ReeseÕs Miniatures         1      0       0              1      0
53   ReeseÕs Peanut Butter cup         1      0       0              1      0
54              ReeseÕs pieces         1      0       0              1      0
55 ReeseÕs stuffed with pieces         1      0       0              1      0
56                    Ring pop         0      1       0              0      0
57                        Rolo         1      0       1              0      0
58           Root Beer Barrels         0      0       0              0      0
59                       Runts         0      1       0              0      0
60                     Sixlets         1      0       0              0      0
61           Skittles original         0      1       0              0      0
62          Skittles wildberry         0      1       0              0      0
63             Nestle Smarties         1      0       0              0      0
64              Smarties candy         0      1       0              0      0
65                    Snickers         1      0       1              1      1
66            Snickers Crisper         1      0       1              1      0
67             Sour Patch Kids         0      1       0              0      0
68       Sour Patch Tricksters         0      1       0              0      0
69                   Starburst         0      1       0              0      0
70         Strawberry bon bons         0      1       0              0      0
71                Sugar Babies         0      0       1              0      0
72                 Sugar Daddy         0      0       1              0      0
73                Super Bubble         0      1       0              0      0
74                Swedish Fish         0      1       0              0      0
75                 Tootsie Pop         1      1       0              0      0
76        Tootsie Roll Juniors         1      0       0              0      0
77        Tootsie Roll Midgies         1      0       0              0      0
78     Tootsie Roll Snack Bars         1      0       0              0      0
79           Trolli Sour Bites         0      1       0              0      0
80                        Twix         1      0       1              0      0
81                   Twizzlers         0      1       0              0      0
82                    Warheads         0      1       0              0      0
83        WelchÕs Fruit Snacks         0      1       0              0      0
84  WertherÕs Original Caramel         0      0       1              0      0
85                    Whoppers         1      0       0              0      0
   crispedricewafer hard bar pluribus sugarpercent pricepercent winpercent
1                 1    0   1        0        0.732        0.860   66.97173
2                 0    0   1        0        0.604        0.511   67.60294
3                 0    0   0        0        0.011        0.116   32.26109
4                 0    0   0        0        0.011        0.511   46.11650
5                 0    0   0        0        0.906        0.511   52.34146
6                 0    0   1        0        0.465        0.767   50.34755
7                 0    0   1        0        0.604        0.767   56.91455
8                 0    0   0        1        0.313        0.511   23.41782
9                 0    0   0        1        0.906        0.325   38.01096
10                0    0   0        0        0.604        0.325   34.51768
11                0    0   1        0        0.604        0.511   38.97504
12                0    0   0        1        0.732        0.511   36.01763
13                0    0   0        1        0.046        0.325   24.52499
14                0    0   0        1        0.732        0.511   42.27208
15                0    1   0        0        0.732        0.034   39.46056
16                0    0   0        1        0.127        0.034   43.08892
17                0    1   0        0        0.732        0.325   39.18550
18                0    1   0        1        0.906        0.453   46.78335
19                0    0   0        1        0.465        0.465   57.11974
20                0    0   0        1        0.465        0.465   34.15896
21                0    0   0        1        0.465        0.465   51.41243
22                0    0   0        1        0.465        0.465   42.17877
23                0    0   0        1        0.127        0.093   55.37545
24                1    0   1        0        0.430        0.918   62.28448
25                0    0   1        0        0.430        0.918   56.49050
26                0    0   1        0        0.430        0.918   59.23612
27                0    1   0        1        0.093        0.511   28.12744
28                0    0   0        1        0.197        0.511   57.21925
29                1    0   1        0        0.313        0.511   76.76860
30                0    0   0        0        0.220        0.116   41.38956
31                0    1   0        0        0.046        0.104   39.14106
32                0    0   0        0        0.267        0.279   52.91139
33                0    0   0        1        0.825        0.651   71.46505
34                0    0   0        1        0.825        0.651   66.57458
35                0    0   0        1        0.872        0.325   46.41172
36                0    0   0        1        0.302        0.511   55.06407
37                0    0   1        0        0.604        0.651   73.09956
38                0    0   1        0        0.732        0.441   60.80070
39                0    0   1        0        0.965        0.860   64.35334
40                0    0   1        0        0.313        0.860   47.82975
41                0    0   1        0        0.313        0.918   54.52645
42                0    1   0        1        0.848        0.325   55.35405
43                0    0   1        0        0.604        0.767   70.73564
44                1    0   1        0        0.313        0.767   66.47068
45                0    0   0        1        0.197        0.976   22.44534
46                0    0   0        1        0.220        0.325   39.44680
47                0    0   1        0        0.465        0.767   46.29660
48                0    0   0        1        0.593        0.651   69.48379
49                0    0   0        1        0.093        0.023   37.72234
50                0    1   0        1        0.604        0.837   41.26551
51                0    0   0        1        0.581        0.116   37.34852
52                0    0   0        0        0.034        0.279   81.86626
53                0    0   0        0        0.720        0.651   84.18029
54                0    0   0        1        0.406        0.651   73.43499
55                0    0   0        0        0.988        0.651   72.88790
56                0    1   0        0        0.732        0.965   35.29076
57                0    0   0        1        0.860        0.860   65.71629
58                0    1   0        1        0.732        0.069   29.70369
59                0    1   0        1        0.872        0.279   42.84914
60                0    0   0        1        0.220        0.081   34.72200
61                0    0   0        1        0.941        0.220   63.08514
62                0    0   0        1        0.941        0.220   55.10370
63                0    0   0        1        0.267        0.976   37.88719
64                0    1   0        1        0.267        0.116   45.99583
65                0    0   1        0        0.546        0.651   76.67378
66                1    0   1        0        0.604        0.651   59.52925
67                0    0   0        1        0.069        0.116   59.86400
68                0    0   0        1        0.069        0.116   52.82595
69                0    0   0        1        0.151        0.220   67.03763
70                0    1   0        1        0.569        0.058   34.57899
71                0    0   0        1        0.965        0.767   33.43755
72                0    0   0        0        0.418        0.325   32.23100
73                0    0   0        0        0.162        0.116   27.30386
74                0    0   0        1        0.604        0.755   54.86111
75                0    1   0        0        0.604        0.325   48.98265
76                0    0   0        0        0.313        0.511   43.06890
77                0    0   0        1        0.174        0.011   45.73675
78                0    0   1        0        0.465        0.325   49.65350
79                0    0   0        1        0.313        0.255   47.17323
80                1    0   1        0        0.546        0.906   81.64291
81                0    0   0        0        0.220        0.116   45.46628
82                0    1   0        0        0.093        0.116   39.01190
83                0    0   0        1        0.313        0.313   44.37552
84                0    1   0        0        0.186        0.267   41.90431
85                1    0   0        1        0.872        0.848   49.52411</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>candy <span class="ot">&lt;-</span>  <span class="fu">read.csv</span>(candy_file, <span class="at">row.names=</span><span class="dv">1</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             chocolate fruity caramel peanutyalmondy nougat crispedricewafer
100 Grand            1      0       1              0      0                1
3 Musketeers         1      0       0              0      1                0
One dime             0      0       0              0      0                0
One quarter          0      0       0              0      0                0
Air Heads            0      1       0              0      0                0
Almond Joy           1      0       0              1      0                0
             hard bar pluribus sugarpercent pricepercent winpercent
100 Grand       0   1        0        0.732        0.860   66.97173
3 Musketeers    0   1        0        0.604        0.511   67.60294
One dime        0   0        0        0.011        0.116   32.26109
One quarter     0   0        0        0.011        0.511   46.11650
Air Heads       0   0        0        0.906        0.511   52.34146
Almond Joy      0   1        0        0.465        0.767   50.34755</code></pre>
</div>
</div>
<section id="what-is-in-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="what-is-in-the-dataset">What is in the dataset?</h3>
<blockquote class="blockquote">
<p>Q1. How many different candy types are in this dataset?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 85</code></pre>
</div>
</div>
<ul>
<li>85 different types of candy.</li>
</ul>
<blockquote class="blockquote">
<p>Q2. How many fruity candy types are in the dataset?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(candy<span class="sc">$</span>fruity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38</code></pre>
</div>
</div>
<ul>
<li>38 fruity candy types.</li>
</ul>
</section>
</section>
<section id="what-is-your-favorite-candy" class="level2">
<h2 class="anchored" data-anchor-id="what-is-your-favorite-candy">What is your favorite candy?</h2>
<blockquote class="blockquote">
<p>Q3. What is your favorite candy in the dataset and what is it’s winpercent value?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Junior Mints"</span>, ]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 57.21925</code></pre>
</div>
</div>
<ul>
<li>My favorite candy in the dataset is Junior Mints. Its winpercent value is 57.21925</li>
</ul>
<blockquote class="blockquote">
<p>Q4. What is the winpercent value for “Kit Kat”?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Kit Kat"</span>, ]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 76.7686</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q5. What is the winpercent value for “Tootsie Roll Snack Bars”?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>candy[<span class="st">"Tootsie Roll Snack Bars"</span>, ]<span class="sc">$</span>winpercent</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 49.6535</code></pre>
</div>
</div>
<p><strong>Side Note:</strong> <code>skim()</code> can give a quick overview of a given dataset. Install the skimr package and try it on our candy data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>skimr<span class="sc">::</span><span class="fu">skim</span>(candy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">candy</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">chocolate</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">fruity</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">caramel</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">peanutyalmondy</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nougat</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">crispedricewafer</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hard</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">bar</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pluribus</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">▇▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">sugarpercent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">▇▇▇▇▆</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pricepercent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.47</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: left;">▇▇▇▇▆</td>
</tr>
<tr class="even">
<td style="text-align: left;">winpercent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">50.32</td>
<td style="text-align: right;">14.71</td>
<td style="text-align: right;">22.45</td>
<td style="text-align: right;">39.14</td>
<td style="text-align: right;">47.83</td>
<td style="text-align: right;">59.86</td>
<td style="text-align: right;">84.18</td>
<td style="text-align: left;">▃▇▆▅▂</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p>Q6. Is there any variable/column that looks to be on a different scale to the majority of the other columns in the dataset?</p>
</blockquote>
<ul>
<li>winpercent is on a scale of 0-100 while the other variables are on a 0-1 scale.</li>
</ul>
<blockquote class="blockquote">
<p>Q7. What do you think a zero and one represent for the candy$chocolate column?</p>
</blockquote>
<ul>
<li>A zero means there is no chocolate in the candy and a 1 means there is chocolate in the candy.</li>
</ul>
<blockquote class="blockquote">
<p>Q8. Plot a histogram of winpercent values</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(candy<span class="sc">$</span>winpercent)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>OR we can use ggplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"orange"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q9. Is the distribution of winpercent values symmetrical?</p>
</blockquote>
<ul>
<li>The winpercent values are skewed toward the left.</li>
</ul>
<blockquote class="blockquote">
<p>Q10. Is the center of the distribution above or below 50%?</p>
</blockquote>
<ul>
<li>The center is below 50%.</li>
</ul>
<blockquote class="blockquote">
<p>Q11. On average is chocolate candy higher or lower ranked than fruit candy?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>chocolate.inds <span class="ot">&lt;-</span> <span class="fu">as.logical</span>(candy<span class="sc">$</span>chocolate)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>chocolate.wins <span class="ot">&lt;-</span> candy[chocolate.inds, ]<span class="sc">$</span>winpercent</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(chocolate.wins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60.92153</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fruity.inds <span class="ot">&lt;-</span> <span class="fu">as.logical</span>(candy<span class="sc">$</span>fruity)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>fruity.wins <span class="ot">&lt;-</span> candy[fruity.inds, ]<span class="sc">$</span>winpercent</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(fruity.wins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 44.11974</code></pre>
</div>
</div>
<ul>
<li>Chocolate candy is ranked higher than fruity candy on average.</li>
</ul>
<blockquote class="blockquote">
<p>Q12. Is this difference statistically significant?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chocolate.wins, fruity.wins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  chocolate.wins and fruity.wins
t = 6.2582, df = 68.882, p-value = 2.871e-08
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 11.44563 22.15795
sample estimates:
mean of x mean of y 
 60.92153  44.11974 </code></pre>
</div>
</div>
<ul>
<li>The p-value is less than 0.05, so the difference is statistically significant.</li>
</ul>
</section>
<section id="overall-candy-rankings" class="level2">
<h2 class="anchored" data-anchor-id="overall-candy-rankings">Overall Candy Rankings</h2>
<blockquote class="blockquote">
<p>Q13. What are the five least liked candy types in this set?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(candy[<span class="fu">order</span>(candy<span class="sc">$</span>winpercent), ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   chocolate fruity caramel peanutyalmondy nougat
Nik L Nip                  0      1       0              0      0
Boston Baked Beans         0      0       0              1      0
Chiclets                   0      1       0              0      0
Super Bubble               0      1       0              0      0
Jawbusters                 0      1       0              0      0
Root Beer Barrels          0      0       0              0      0
                   crispedricewafer hard bar pluribus sugarpercent pricepercent
Nik L Nip                         0    0   0        1        0.197        0.976
Boston Baked Beans                0    0   0        1        0.313        0.511
Chiclets                          0    0   0        1        0.046        0.325
Super Bubble                      0    0   0        0        0.162        0.116
Jawbusters                        0    1   0        1        0.093        0.511
Root Beer Barrels                 0    1   0        1        0.732        0.069
                   winpercent
Nik L Nip            22.44534
Boston Baked Beans   23.41782
Chiclets             24.52499
Super Bubble         27.30386
Jawbusters           28.12744
Root Beer Barrels    29.70369</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q14. What are the top 5 all time favorite candy types out of this set?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(candy[<span class="fu">order</span>(candy<span class="sc">$</span>winpercent), ])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          chocolate fruity caramel peanutyalmondy nougat
ReeseÕs pieces                    1      0       0              1      0
Snickers                          1      0       1              1      1
Kit Kat                           1      0       0              0      0
Twix                              1      0       1              0      0
ReeseÕs Miniatures                1      0       0              1      0
ReeseÕs Peanut Butter cup         1      0       0              1      0
                          crispedricewafer hard bar pluribus sugarpercent
ReeseÕs pieces                           0    0   0        1        0.406
Snickers                                 0    0   1        0        0.546
Kit Kat                                  1    0   1        0        0.313
Twix                                     1    0   1        0        0.546
ReeseÕs Miniatures                       0    0   0        0        0.034
ReeseÕs Peanut Butter cup                0    0   0        0        0.720
                          pricepercent winpercent
ReeseÕs pieces                   0.651   73.43499
Snickers                         0.651   76.67378
Kit Kat                          0.511   76.76860
Twix                             0.906   81.64291
ReeseÕs Miniatures               0.279   81.86626
ReeseÕs Peanut Butter cup        0.651   84.18029</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q15. Make a first barplot of candy ranking based on winpercent values.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, <span class="fu">rownames</span>(candy)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q16. This is quite ugly, use the reorder() function to get the bars sorted by winpercent?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, <span class="fu">reorder</span>(<span class="fu">rownames</span>(candy), winpercent)) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"plum"</span>, <span class="at">col =</span> <span class="st">"orange"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="time-to-add-some-useful-color" class="level3">
<h3 class="anchored" data-anchor-id="time-to-add-some-useful-color">Time to add some useful color</h3>
<p>Let’s set up a color vector that signifies candy type. Start by making a vector of all black values then we overwrite chocolate, brown, and red.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>my_cols<span class="ot">=</span><span class="fu">rep</span>(<span class="st">"black"</span>, <span class="fu">nrow</span>(candy))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>my_cols[<span class="fu">as.logical</span>(candy<span class="sc">$</span>chocolate)] <span class="ot">=</span> <span class="st">"chocolate"</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>my_cols[<span class="fu">as.logical</span>(candy<span class="sc">$</span>bar)] <span class="ot">=</span> <span class="st">"brown"</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>my_cols[<span class="fu">as.logical</span>(candy<span class="sc">$</span>fruity)] <span class="ot">=</span> <span class="st">"pink"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s try our barplot with the new colors</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, <span class="fu">reorder</span>(<span class="fu">rownames</span>(candy), winpercent)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> my_cols)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Save the plot as an image:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"tmp.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Saving 7 x 5 in image</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Q17. What is the worst ranked chocolate candy?</p>
</blockquote>
<ul>
<li>Sixlets</li>
</ul>
<blockquote class="blockquote">
<p>Q18. What is the best ranked fruity candy?</p>
</blockquote>
<ul>
<li>Starburst</li>
</ul>
</section>
</section>
<section id="taking-a-look-at-pricepercent" class="level2">
<h2 class="anchored" data-anchor-id="taking-a-look-at-pricepercent">Taking a Look at Pricepercent</h2>
<p>Make a plot of winpercent vs pricepercent:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(candy) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(winpercent, pricepercent, <span class="at">label=</span><span class="fu">rownames</span>(candy)) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">col=</span>my_cols) <span class="sc">+</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="at">col=</span>my_cols, <span class="at">size=</span><span class="fl">3.3</span>, <span class="at">max.overlaps =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: ggrepel: 20 unlabeled data points (too many overlaps). Consider
increasing max.overlaps</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Order the candy by pricepercent:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ord <span class="ot">&lt;-</span> <span class="fu">order</span>(candy<span class="sc">$</span>pricepercent, <span class="at">decreasing =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>Q19. Which candy type is the highest ranked in terms of winpercent for the least money - i.e.&nbsp;offers the most bang for your buck?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>candy[(<span class="fu">order</span>(candy<span class="sc">$</span>winpercent, <span class="at">decreasing =</span> T)), <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">12</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            pricepercent winpercent
ReeseÕs Peanut Butter cup          0.651   84.18029
ReeseÕs Miniatures                 0.279   81.86626
Twix                               0.906   81.64291
Kit Kat                            0.511   76.76860
Snickers                           0.651   76.67378
ReeseÕs pieces                     0.651   73.43499
Milky Way                          0.651   73.09956
ReeseÕs stuffed with pieces        0.651   72.88790
Peanut butter M&amp;MÕs                0.651   71.46505
Nestle Butterfinger                0.767   70.73564
Peanut M&amp;Ms                        0.651   69.48379
3 Musketeers                       0.511   67.60294
Starburst                          0.220   67.03763
100 Grand                          0.860   66.97173
M&amp;MÕs                              0.651   66.57458
Nestle Crunch                      0.767   66.47068
Rolo                               0.860   65.71629
Milky Way Simply Caramel           0.860   64.35334
Skittles original                  0.220   63.08514
HersheyÕs Krackel                  0.918   62.28448
Milky Way Midnight                 0.441   60.80070
Sour Patch Kids                    0.116   59.86400
Snickers Crisper                   0.651   59.52925
HersheyÕs Special Dark             0.918   59.23612
Junior Mints                       0.511   57.21925
Haribo Gold Bears                  0.465   57.11974
Baby Ruth                          0.767   56.91455
HersheyÕs Milk Chocolate           0.918   56.49050
HersheyÕs Kisses                   0.093   55.37545
Nerds                              0.325   55.35405
Skittles wildberry                 0.220   55.10370
Milk Duds                          0.511   55.06407
Swedish Fish                       0.755   54.86111
Mr Good Bar                        0.918   54.52645
Lifesavers big ring gummies        0.279   52.91139
Sour Patch Tricksters              0.116   52.82595
Air Heads                          0.511   52.34146
Haribo Sour Bears                  0.465   51.41243
Almond Joy                         0.767   50.34755
Tootsie Roll Snack Bars            0.325   49.65350
Whoppers                           0.848   49.52411
Tootsie Pop                        0.325   48.98265
Mounds                             0.860   47.82975
Trolli Sour Bites                  0.255   47.17323
Gobstopper                         0.453   46.78335
Mike &amp; Ike                         0.325   46.41172
Payday                             0.767   46.29660
One quarter                        0.511   46.11650
Smarties candy                     0.116   45.99583
Tootsie Roll Midgies               0.011   45.73675
Twizzlers                          0.116   45.46628
WelchÕs Fruit Snacks               0.313   44.37552
Fruit Chews                        0.034   43.08892
Tootsie Roll Juniors               0.511   43.06890
Runts                              0.279   42.84914
Dots                               0.511   42.27208
Haribo Twin Snakes                 0.465   42.17877
WertherÕs Original Caramel         0.267   41.90431
Laffy Taffy                        0.116   41.38956
Pop Rocks                          0.837   41.26551
Dum Dums                           0.034   39.46056
Now &amp; Later                        0.325   39.44680
Fun Dip                            0.325   39.18550
Lemonhead                          0.104   39.14106
Warheads                           0.116   39.01190
Charleston Chew                    0.511   38.97504
Candy Corn                         0.325   38.01096
Nestle Smarties                    0.976   37.88719
Pixie Sticks                       0.023   37.72234
Red vines                          0.116   37.34852
Chewey Lemonhead Fruit Mix         0.511   36.01763
Ring pop                           0.965   35.29076
Sixlets                            0.081   34.72200
Strawberry bon bons                0.058   34.57899
Caramel Apple Pops                 0.325   34.51768
Haribo Happy Cola                  0.465   34.15896
Sugar Babies                       0.767   33.43755
One dime                           0.116   32.26109
Sugar Daddy                        0.325   32.23100
Root Beer Barrels                  0.069   29.70369
Jawbusters                         0.511   28.12744
Super Bubble                       0.116   27.30386
Chiclets                           0.325   24.52499
Boston Baked Beans                 0.511   23.41782
Nik L Nip                          0.976   22.44534</code></pre>
</div>
</div>
<ul>
<li>Reese’s Miniatures has a pricepercent value of 0.279 and a winpercent value of 81.86626</li>
</ul>
<blockquote class="blockquote">
<p>Q20. What are the top 5 most expensive candy types in the dataset and of these which is the least popular?</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(candy[ord, <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">12</span>)], <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         pricepercent winpercent
Nik L Nip                       0.976   22.44534
Nestle Smarties                 0.976   37.88719
Ring pop                        0.965   35.29076
HersheyÕs Krackel               0.918   62.28448
HersheyÕs Milk Chocolate        0.918   56.49050</code></pre>
</div>
</div>
<ul>
<li>Nik L Nip is the least popular of the most expensive candies.</li>
</ul>
</section>
<section id="exploring-the-correlation-structure" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-correlation-structure">Exploring the Correlation Structure</h2>
<p>Let’s see how the variables interact with one another using the corrplot package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>cij <span class="ot">&lt;-</span> <span class="fu">cor</span>(candy)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cij)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q22. Examining this plot what two variables are anti-correlated (i.e.&nbsp;have minus values)?</p>
</blockquote>
<ul>
<li>fruity and chocolate.</li>
</ul>
<blockquote class="blockquote">
<p>Q23. Similarly, what two variables are most positively correlated?</p>
</blockquote>
<ul>
<li>winpercent and chocolate.</li>
</ul>
</section>
<section id="principal-component-analysis" class="level2">
<h2 class="anchored" data-anchor-id="principal-component-analysis">Principal Component Analysis</h2>
<p>Apply PCA using the <code>prcom()</code> function to our candy dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>pca <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(candy, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2    PC3     PC4    PC5     PC6     PC7
Standard deviation     2.0788 1.1378 1.1092 1.07533 0.9518 0.81923 0.81530
Proportion of Variance 0.3601 0.1079 0.1025 0.09636 0.0755 0.05593 0.05539
Cumulative Proportion  0.3601 0.4680 0.5705 0.66688 0.7424 0.79830 0.85369
                           PC8     PC9    PC10    PC11    PC12
Standard deviation     0.74530 0.67824 0.62349 0.43974 0.39760
Proportion of Variance 0.04629 0.03833 0.03239 0.01611 0.01317
Cumulative Proportion  0.89998 0.93832 0.97071 0.98683 1.00000</code></pre>
</div>
</div>
<p>Now we can plot our main PCA score plot of PC1 vs PC2</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pca<span class="sc">$</span>x[, <span class="dv">1</span>], pca<span class="sc">$</span>x[, <span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Change the plotting character and add some color:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pca<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>], <span class="at">col=</span>my_cols, <span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can make a new data.frame that contains our PCA results with the rest of the candy data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(candy, pca<span class="sc">$</span>x[,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data.frame can be used to make a nicer plot using ggplot2:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(my_data) <span class="sc">+</span> </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">aes</span>(<span class="at">x=</span>PC1, <span class="at">y=</span>PC2, </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">size=</span>winpercent<span class="sc">/</span><span class="dv">100</span>,  </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">text=</span><span class="fu">rownames</span>(my_data),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">label=</span><span class="fu">rownames</span>(my_data)) <span class="sc">+</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_point</span>(<span class="at">col=</span>my_cols)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Use ggrepel to add labels:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>p <span class="sc">+</span> <span class="fu">geom_text_repel</span>(<span class="at">size=</span><span class="fl">3.3</span>, <span class="at">col=</span>my_cols, <span class="at">max.overlaps =</span> <span class="dv">7</span>)  <span class="sc">+</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Halloween Candy PCA Space"</span>,</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle=</span><span class="st">"Colored by type: chocolate bar (dark brown), chocolate other (light brown), fruity (red), other (black)"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption=</span><span class="st">"Data from 538"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: ggrepel: 41 unlabeled data points (too many overlaps). Consider
increasing max.overlaps</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Make a barplot of our findings:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(pca<span class="sc">$</span>rotation[,<span class="dv">1</span>], <span class="at">las=</span><span class="dv">2</span>, <span class="at">ylab=</span><span class="st">"PC1 Contribution"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Class10_render_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<blockquote class="blockquote">
<p>Q24. What original variables are picked up strongly by PC1 in the positive direction? Do these make sense to you?</p>
</blockquote>
<ul>
<li>fruity, hard, and pluribus.</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>